CREATE SCHEMA IF NOT EXISTS supabase_migrations;
CREATE TABLE IF NOT EXISTS supabase_migrations.schema_migrations (
    version character varying(255) NOT NULL,
    statements text[],
    name character varying(255),
    CONSTRAINT schema_migrations_pkey PRIMARY KEY (version)
);

INSERT INTO supabase_migrations.schema_migrations (version, statements, name) VALUES
('001', '{}', 'initial_schema'),
('002', '{}', 'sponsors_reportes'),
('003', '{}', 'news_flashes'),
('004', '{}', 'site_settings'),
('005', '{}', 'admin_policies'),
('006', '{}', 'public_articles'),
('007', '{}', 'itec_actions'),
('008', '{}', 'storage_buckets'),
('009', '{}', 'videoteca'),
('010', '{}', 'video_summary'),
('011', '{}', 'allowed_emails'),
('0121', '{}', 'whatsapp_templates'),
('012', '{}', 'full_pre_approval'),
('0131', '{}', 'whatsapp_contacts_groups'),
('013', '{}', 'drive_credentials'),
('0141', '{}', 'fix_actions_rls'),
('014', '{}', 'drive_folder_ids'),
('015', '{}', 'google_service_account'),
('016', '{}', 'encuestas'),
('017', '{}', 'encuestas_v2'),
('018', '{}', 'encuestas_chart_type'),
('019', '{}', 'evento_preguntas_schema'),
('020', '{}', 'evento_preguntas_colaborador'),
('021', '{}', 'nube_ideas_multinube'),
('022', '{}', 'article_related_video'),
('023', '{}', 'asistente_aprendizajes'),
('0241', '{}', 'clases_y_certificados'),
('024', '{}', 'asistente_embeddings'),
('0251', '{}', 'clases_en_vivo'),
('025', '{}', 'ai_prompt_settings'),
('0261', '{}', 'sistema_eventos_qr_unificado'),
('026', '{}', 'ai_auditoria_violaciones'),
('027', '{}', 'storage_avatars'),
('028', '{}', 'miembros_publicos_rpc'),
('029', '{}', 'members_delete_policy'),
('030', '{}', 'mapa_empresas_telefono'),
('031', '{}', 'add_avatar_to_public_members'),
('0321', '{}', 'fix_email_case_trigger'),
('032', '{}', 'add_more_fields_to_public_members'),
('033', '{}', 'news_multicanal'),
('034', '{}', 'news_multicanal_fix'),
('035', '{}', 'news_comments'),
('0361', '{}', 'sponsors_campos'),
('036', '{}', 'news_media'),
('037', '{}', 'notas_generadas'),
('038', '{}', 'add_titulo_to_news_flashes'),
('039', '{}', 'add_media_urls_to_sponsors_medios'),
('040', '{}', 'add_news_flash_id_to_public_articles'),
('041', '{}', 'chat_conocimiento'),
('042', '{}', 'training_docs_storage'),
('043', '{}', 'fix_training_docs_policies'),
('044', '{}', 'buscar_docs_similares'),
('045', '{}', 'saved_conversations'),
('046', '{}', 'ideas_table'),
('047', '{}', 'prensa_envios_log'),
('048', '{}', 'ideas_delete_policy'),
('049', '{}', 'evento_semaforo'),
('050', '{}', 'fix_eventos_modalidad'),
('051', '{}', 'evento_herramientas_jsonb'),
('052', '{}', 'herramientas_default_false')
ON CONFLICT (version) DO NOTHING;