services:
  - type: web
    name: itec-asistente-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: false
    envVars:
      - key: PORT
        value: 8000
      - key: GROQ_API_KEY
        sync: false
